# Important Notes:
# fabric.mod.json's modid field cannot be expanded, you must change it manually.
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=13.0.0+26.1
group=com.illusivesoulworks.customfov
java_version=25

# Common
minecraft_version=26.1
mod_name=Custom FOV
mod_author=Illusive Soulworks
mod_id=customfov
license=LGPL-3.0-or-later
issues_url=https://github.com/illusivesoulworks/customfov/issues
sources_url=https://github.com/illusivesoulworks/customfov
description=Allows customization of various field of view settings.
minecraft_version_range=[26.1, 27)
minecraft_version_range_alt=~26.1

## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1-1

# Fabric
fabric_version=0.144.3+26.1
fabric_loader_version=0.18.4

# Forge
forge_version=62.0.2
forge_version_range=[62,)

# NeoForge
neoforge_version=26.1.0.1-beta
neoforge_version_range=[26.1,)

# Publishing
cf_id=303938
cf_page=https://www.curseforge.com/minecraft/mc-mods/custom-fov
modrinth_id=uZAcFHLd
modrinth_page=https://modrinth.com/mod/custom-fov-illusive
release_type=release
release_versions=26.1
changelog_link=https://github.com/illusivesoulworks/customfov/blob/26.x/CHANGELOG.md
discord_thumbnail=https://media.forgecdn.net/avatars/225/688/637041334147160730.png

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
